### ISSUE TITLE
What the algorithm is used for balancing Hi-C matrix?

### ISSUE THREAD

**Issue by shappiron** [open2c/distiller-nf#154]
I'm new in using distiller-nf. It would be interesting to know about balancing (iterative correction) algorithms lies behind.

**Comment by Phlya** [comment]
Balancing is performed using the cooler package. Balancing is described in the supplementary cooler paper https://academic.oup.com/bioinformatics/article/36/1/311/5530598, but basically it's the same as in the Imakaev 2012 paper https://dx.doi.org/10.1038/nmeth.2148. That is, it's Sinkhorn-Knopp matrix balancing, with bin-level filtering to ignore coverage outliers which would otherwise prevent or severely slow down the convergence (and even cause artificial values). For details and options you can have a look at the `cooler balance` documentation too https://cooler.readthedocs.io/en/latest/cli.html#cooler-balance
