### ISSUE TITLE
fastp missing from docker image?

### ISSUE THREAD

**Issue by ChristopherBarrington** [open2c/distiller-nf#159]
https://github.com/open2c/distiller-nf/blob/4236152b1d3a6ce38f82af257fd837833b782a67/docker/conda.list#L29

We had an issue that fastp could not be found when running the pipeline via docker. It looks like fastp is missing from the list of packages to include in the image? We could still run the pipeline by not using the Docker image.

Thanks!

**Comment by gspracklin** [comment]
Yes. In configs/local.config set docker = False and it should be fine. We'll update the docker image soon.

https://github.com/gspracklin/distiller-nf/blob/27d6a384263e03f2aa8770c08121073edc54a1a9/configs/local.config#L71

**Comment by chorzow** [comment]
Hello everyone,

I am facing the same issue when try to launch the pipeline using singularity. @ChristopherBarrington could you share how to run distiller without using the Docker image? I am trying to run the test example as described in README but it fails because fastp is missing although it is installed in my conda environment (fastp 0.12.4). Am I missing something?

**Comment by agalitsyna** [comment]
Resolved in the distiller 0.3.4 release https://github.com/open2c/distiller-nf/releases/tag/v0.3.4
Feel free to re-open if any dependency is missing.
